common-files:
  bot_branch_name: broadcast-common-files
  patterns_to_include: >
    .gitattributes, .editorconfig, .gitignore
  destination: .
  commit_message: |
    chore: [skip ci] update of common files
    Files in the scope:
    - .gitattributes
    - .editorconfig
    - .gitignore
    Docs: https://github.com/Netcracker/qubership-workflow-hub#common-workflows
    Issue: https://github.com/Netcracker/qubership-workflow-hub/issues/249
common-workflows:
  patterns_to_include: >
    workflow-templates/cla.yaml,
    workflow-templates/super-linter.yaml,
    workflow-templates/profanity-filter.yaml,
    workflow-templates/automatic-pr-labeler.yaml,
    workflow-templates/pr-conventional-commits.yaml,
    workflow-templates/pr-lint-title.yaml,
    workflow-templates/link-checker.yaml
    workflow-templates/ossf-scorecard.yaml
  destination: .github/workflows
  repos_to_ignore: >
    KubeMarine, k8s-conformance, gatekeeper-library,
    cassandra-exporter, pg_hint_plan
  bot_branch_name: broadcast-workflows
  commit_message: 'chore: [skip ci] update of common workflows'
