---
name: Broadcast files to organization
on:
  workflow_dispatch:
    inputs:
      repos:
        description: |
          Target repositorys names. Comma-separated
          If not provided, the action will be triggered for all repositories in the organization.
        required: false
        type: string
      replicate-common-files:
        description: 'Replicate common files'
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pull-requests: write
  statuses: read
jobs:
  setup_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup_matrix.outputs.matrix }}
    steps:
      - id: setup_matrix
        run: |
          CSV_STRING="${{ inputs.repos }}"
          JSON_MATRIX=$(jq -c -n --arg in_str "$CSV_STRING" '$in_str | split(",")')
          echo "matrix={\"item\":$JSON_MATRIX}"
          echo "matrix={\"item\":$JSON_MATRIX}" >> $GITHUB_OUTPUT

  replicate_common_files:
    needs: setup_matrix
    name: Replicating common git files
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup_matrix.outputs.matrix) }}
    if: ${{ inputs.replicate-common-files }}
    uses: myborislavrorg/broadcast/.github/workflows/reusable-broadcast-files.yaml@main
    with:
      replicate-common-files: ${{ inputs.replicate-common-files }}
      repo_name: "${{ matrix.item }}"
    secrets:
      token: '${{ secrets.GITHUB_TOKEN }}'
